/*
 * Copyright (C) 2020 util2
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.wingate.ygg.ui;

import java.awt.BorderLayout;
import org.wingate.timelibrary.Time;
import org.wingate.ygg.subs.ass.AssEvent;
import org.wingate.ygg.ui.synctable.AssLinkPanel;
import org.wingate.ygg.ui.synctable.SelectedFormat;
import org.wingate.ygg.ui.synctable.SrtLinkPanel;
import org.wingate.ygg.ui.synctable.SsbLinkPanel;
import org.wingate.ygg.ui.synctable.VesLinkPanel;
import org.wingate.ygg.ui.synctable.WebVTTLinkPanel;

/**
 *
 * @author util2
 */
public class IfrTableLink extends javax.swing.JInternalFrame {

    private final AssLinkPanel assLink = new AssLinkPanel();
    private final SrtLinkPanel srtLink = new SrtLinkPanel();
    private final SsbLinkPanel ssbLink = new SsbLinkPanel();
    private final VesLinkPanel vesLink = new VesLinkPanel();
    private final WebVTTLinkPanel vttLink = new WebVTTLinkPanel();
    
    private SelectedFormat selectedFormat = SelectedFormat.ASS;
    
    /**
     * Creates new form IfrTableLink
     */
    public IfrTableLink() {
        initComponents();
        init();
    }
    
    private void init(){
        changeLink();
    }

    public SelectedFormat getSelectedFormat() {
        return selectedFormat;
    }

    public void setSelectedFormat(SelectedFormat selectedFormat) {
        this.selectedFormat = selectedFormat;
        changeLink();
    }
    
    public void changeLink(){
        if(panLink.getComponentCount() > 0){
            panLink.removeAll();
        }        
        switch(selectedFormat){
            case ASS -> { panLink.add(assLink, BorderLayout.CENTER); }
            case SRT -> { panLink.add(srtLink, BorderLayout.CENTER); }
            case SSB -> { panLink.add(ssbLink, BorderLayout.CENTER); }
            case VES -> { panLink.add(vesLink, BorderLayout.CENTER); }
            case WebVTT -> { panLink.add(vttLink, BorderLayout.CENTER); }
        }
    }

    public AssLinkPanel getAssLink() {
        return assLink;
    }

    public SrtLinkPanel getSrtLink() {
        return srtLink;
    }

    public SsbLinkPanel getSsbLink() {
        return ssbLink;
    }

    public VesLinkPanel getVesLink() {
        return vesLink;
    }

    public WebVTTLinkPanel getVttLink() {
        return vttLink;
    }
    
    public void setStartTime(Time start){
        switch(selectedFormat){
            case ASS -> {
                AssEvent ev = (AssEvent) assLink.getFromAssSubCommands();
                ev.setStartTime(start);
                assLink.alter(ev);
            }
            case SRT -> {
                
            }
            case SSB -> {
                
            }
            case VES -> {
                
            }
            case WebVTT -> {
                
            }
        }
    }
    
    public void setEndTime(Time end){
        switch(selectedFormat){
            case ASS -> {
                AssEvent ev = (AssEvent) assLink.getFromAssSubCommands();
                ev.setEndTime(end);
                assLink.alter(ev);
            }
            case SRT -> {
                
            }
            case SSB -> {
                
            }
            case VES -> {
                
            }
            case WebVTT -> {
                
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panLink = new javax.swing.JPanel();

        setMaximizable(true);
        setResizable(true);
        setTitle("Commands");

        panLink.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panLink, javax.swing.GroupLayout.DEFAULT_SIZE, 867, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panLink, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panLink;
    // End of variables declaration//GEN-END:variables
}
