/*
 * Copyright (C) 2021 util2
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.wingate.ygg.ui;

import java.io.File;
import java.nio.ByteBuffer;
import java.nio.ShortBuffer;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.DataLine;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.SourceDataLine;
import javax.swing.DefaultComboBoxModel;
import org.bytedeco.javacv.FFmpegFrameGrabber;
import org.bytedeco.javacv.FrameGrabber;
import org.wingate.timelibrary.Time;
import org.wingate.ygg.io.subs.ass.ASS;
import org.wingate.ygg.io.subs.ass.Event;
import org.wingate.ygg.languages.ISO_3166;

/**
 *
 * @author util2
 */
public class IfrTranslation extends javax.swing.JInternalFrame {

    private ASS ass = null;
    private long msAreaStart = 0L;
    private long msAreaStop = 0L;
    private final PlayAudio playAudio = new PlayAudio();
    
    // Spécifique à la ligne d'événement active du fichier de sous-titres
    private Event ev = null;        // Evénement en cours
    private int index = 0;          // Numéro de l'événement en cours
    
    private DefaultComboBoxModel dcbmOriginal = new DefaultComboBoxModel();
    private DefaultComboBoxModel dcbmSource = new DefaultComboBoxModel();
    private DefaultComboBoxModel dcbmNew = new DefaultComboBoxModel();
    
    /**
     * Creates new form IfrTranslation
     */
    public IfrTranslation() {
        initComponents();
        init();
    }

    private void init(){
        // Assignation des modèles
        comboOriginal.setModel(dcbmOriginal);
        comboSourceDictionary.setModel(dcbmSource);
        comboNewDictionary.setModel(dcbmNew);
        
        // Remplissage des modèles
        for(ISO_3166 iso : ISO_3166.values()){
            dcbmOriginal.addElement(iso);
        }
        for(ISO_3166 iso : ISO_3166.values()){
            dcbmSource.addElement(iso);
        }
        for(ISO_3166 iso : ISO_3166.values()){
            dcbmNew.addElement(iso);
        }
    }
    
    public void loadASS(File assFile){
        ass = ASS.Read(assFile.getPath());
        if(ass.getEvents().isEmpty() == false){
            ev = ass.getEvents().get(0);
            lblOriginalText.setText(ev.getText());
        }
    }
    
    public void loadAudio(File audioFile){
        try {
            playAudio.setAudio(audioFile);
        } catch (FrameGrabber.Exception | LineUnavailableException ex) {
            Logger.getLogger(IfrTranslation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void saveSubtitles(File folder){
        
    }
    
    public void playArea(){
        if(ev != null && playAudio.getAction() != Action.None){
            msAreaStart = Time.toMillisecondsTime(ev.getStartTime());
            msAreaStop = Time.toMillisecondsTime(ev.getEndTime());

            playAudio.playStopAudio();
        }        
    }
    
    public void thumbnail(){
        if(ev != null && playAudio.getAction() != Action.None){
            msAreaStart = Time.toMillisecondsTime(ev.getStartTime());
            msAreaStop = Time.toMillisecondsTime(ev.getEndTime());
        }
    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgDictionaries = new javax.swing.ButtonGroup();
        tabbedSubs = new javax.swing.JTabbedPane();
        jToolBar1 = new javax.swing.JToolBar();
        btnNewTab = new javax.swing.JButton();
        btnRemoveTab = new javax.swing.JButton();
        btnAddTranslation = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnPlayArea = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnEye = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        panContainer = new javax.swing.JPanel();
        panVideo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblOriginalText = new javax.swing.JLabel();
        comboOriginal = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        panDictionary = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        comboSourceDictionary = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        comboNewDictionary = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        panDictionaries = new javax.swing.JPanel();

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnNewTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/32_plus.png"))); // NOI18N
        btnNewTab.setText("New tab");
        btnNewTab.setFocusable(false);
        btnNewTab.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNewTab.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNewTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewTabActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNewTab);

        btnRemoveTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/32_minus.png"))); // NOI18N
        btnRemoveTab.setText("Remove tab");
        btnRemoveTab.setFocusable(false);
        btnRemoveTab.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRemoveTab.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRemoveTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveTabActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRemoveTab);

        btnAddTranslation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/32 accept.png"))); // NOI18N
        btnAddTranslation.setText("Apply");
        btnAddTranslation.setFocusable(false);
        btnAddTranslation.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddTranslation.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddTranslation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTranslationActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAddTranslation);
        jToolBar1.add(jSeparator1);

        btnPlayArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/32_timer_stuffs in.png"))); // NOI18N
        btnPlayArea.setText("Play area");
        btnPlayArea.setFocusable(false);
        btnPlayArea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlayArea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPlayArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayAreaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPlayArea);
        jToolBar1.add(jSeparator2);

        btnEye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/32_eye.png"))); // NOI18N
        btnEye.setText("Image");
        btnEye.setFocusable(false);
        btnEye.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEye.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEyeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEye);
        jToolBar1.add(jSeparator3);

        btnPrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/32_previous.png"))); // NOI18N
        btnPrevious.setText("Previous");
        btnPrevious.setFocusable(false);
        btnPrevious.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrevious.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPrevious);

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/32_next.png"))); // NOI18N
        btnNext.setText("Next");
        btnNext.setFocusable(false);
        btnNext.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNext.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNext);

        panContainer.setLayout(new java.awt.GridLayout());

        panVideo.setBorder(javax.swing.BorderFactory.createTitledBorder("Subtitles View and Write"));

        jLabel1.setText("Scene :");

        jLabel2.setBackground(new java.awt.Color(51, 102, 255));
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setOpaque(true);

        jLabel3.setText("Text :");

        lblOriginalText.setText("Waiting for text");

        comboOriginal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTextPane1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout panVideoLayout = new javax.swing.GroupLayout(panVideo);
        panVideo.setLayout(panVideoLayout);
        panVideoLayout.setHorizontalGroup(
            panVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panVideoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panVideoLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(comboOriginal, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblOriginalText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panVideoLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panVideoLayout.setVerticalGroup(
            panVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panVideoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panVideoLayout.createSequentialGroup()
                        .addComponent(lblOriginalText, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panContainer.add(panVideo);

        panDictionary.setBorder(javax.swing.BorderFactory.createTitledBorder("Dictionary"));
        panDictionary.setPreferredSize(new java.awt.Dimension(300, 241));

        jLabel5.setText("Source :");

        comboSourceDictionary.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("New :");

        comboNewDictionary.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTextPane2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jScrollPane2.setViewportView(jTextPane2);

        javax.swing.GroupLayout panDictionariesLayout = new javax.swing.GroupLayout(panDictionaries);
        panDictionaries.setLayout(panDictionariesLayout);
        panDictionariesLayout.setHorizontalGroup(
            panDictionariesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panDictionariesLayout.setVerticalGroup(
            panDictionariesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panDictionaryLayout = new javax.swing.GroupLayout(panDictionary);
        panDictionary.setLayout(panDictionaryLayout);
        panDictionaryLayout.setHorizontalGroup(
            panDictionaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDictionaryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panDictionaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(panDictionaryLayout.createSequentialGroup()
                        .addGroup(panDictionaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panDictionaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboSourceDictionary, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboNewDictionary, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addComponent(panDictionaries, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panDictionaryLayout.setVerticalGroup(
            panDictionaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDictionaryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panDictionaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboSourceDictionary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panDictionaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboNewDictionary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panDictionaries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addContainerGap())
        );

        panContainer.add(panDictionary);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedSubs)
            .addComponent(panContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabbedSubs, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewTabActionPerformed
        comboOriginal.getSelectedItem();
    }//GEN-LAST:event_btnNewTabActionPerformed

    private void btnRemoveTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveTabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveTabActionPerformed

    private void btnAddTranslationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTranslationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddTranslationActionPerformed

    private void btnPlayAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayAreaActionPerformed
        playArea();
    }//GEN-LAST:event_btnPlayAreaActionPerformed

    private void btnEyeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEyeActionPerformed
        thumbnail();
    }//GEN-LAST:event_btnEyeActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        if(ass != null && ass.getEvents().isEmpty() == false){
            index = index - 1 > 0 ? index - 1 : 0;
            ev = ass.getEvents().get(index);
            lblOriginalText.setText(ev.getText());
        }
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if(ass != null && ass.getEvents().isEmpty() == false){
            index = index + 1 < ass.getEvents().size() - 1 ? index + 1 : ass.getEvents().size() - 1;
            ev = ass.getEvents().get(index);
            lblOriginalText.setText(ev.getText());
        }
    }//GEN-LAST:event_btnNextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgDictionaries;
    private javax.swing.JButton btnAddTranslation;
    private javax.swing.JButton btnEye;
    private javax.swing.JButton btnNewTab;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPlayArea;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnRemoveTab;
    private javax.swing.JComboBox<String> comboNewDictionary;
    private javax.swing.JComboBox<String> comboOriginal;
    private javax.swing.JComboBox<String> comboSourceDictionary;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblOriginalText;
    private javax.swing.JPanel panContainer;
    private javax.swing.JPanel panDictionaries;
    private javax.swing.JPanel panDictionary;
    private javax.swing.JPanel panVideo;
    private javax.swing.JTabbedPane tabbedSubs;
    // End of variables declaration//GEN-END:variables

    public enum Action {
        None, Ready, Play, Pause, Stop;
    }
    
    class PlayAudio implements Runnable {
    
        private volatile FFmpegFrameGrabber grabber = null;
        private volatile SourceDataLine soundLine = null;
        private volatile ExecutorService executor = Executors.newSingleThreadExecutor();

        private volatile Action action = Action.None;

        private Thread thAct = null;

        private boolean area = false;

        public PlayAudio() {
            init();
        }
        
        private void init(){
            startThread();
        }
        
        public void setAudio(File audio) throws FrameGrabber.Exception, LineUnavailableException{
            // Vérification de la présence de fichier existant
            if(audio.exists() == false){
                action = Action.None;
                return;
            }
            
            // Clôture de la ligne du son si elle existe (lors d'un précédent passage ici)
            if(soundLine != null){
                soundLine.stop();
                soundLine.flush();
                soundLine.drain();
                soundLine.close();
                soundLine = null;
            }
            
            // Clôture du composant FFMpeg s'il existe (lors d'un précédent passage ici)
            if(grabber != null){
                grabber.stop();
                grabber.release();
                grabber = null;
            }
            
            // Lancement du composant FFMpeg (nouveau)
            grabber = new FFmpegFrameGrabber(audio);
            grabber.start();

            // Définition du format audio pour lire le son
            AudioFormat audioFormat = new AudioFormat(
                    grabber.getSampleRate(), 
                    16, 
                    grabber.getAudioChannels(), 
                    true, 
                    true
            );

            // Ouverture d'un processus audio pour le son
            DataLine.Info info = new DataLine.Info(SourceDataLine.class, audioFormat);
            soundLine = (SourceDataLine) AudioSystem.getLine(info);
            soundLine.open(audioFormat);
            soundLine.start();

            // Renseignement de l'état de l'action (état de lecture)
            action = Action.Ready;
        }
        
        public void startThread(){
            stopThread();
            thAct = new Thread(this);
            thAct.start();
        }

        public void stopThread(){
            if(thAct != null && thAct.isInterrupted() == false){
                thAct.interrupt();
                thAct = null;
            }else if(thAct != null && thAct.isInterrupted() == true){
                thAct = null;
            }
        }

        private void endOfFile(){
            try {
                executor.shutdownNow();
                executor.awaitTermination(10, TimeUnit.SECONDS);
            } catch (InterruptedException ex) {
                Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        @Override
        public void run() {
            while(true){
                if(action == Action.Play){
                    try {
                        if(msAreaStart != 0L && area == true){
                            grabber.setAudioTimestamp(msAreaStart * 1000L);
                            area = false;
                        }

                        org.bytedeco.javacv.Frame frame = grabber.grab();

                        if (frame == null) {
                            action = Action.None;
                            continue;
                        }

                        if (frame.samples != null) {
                            ShortBuffer channelSamplesShortBuffer = (ShortBuffer) frame.samples[0];
                            channelSamplesShortBuffer.rewind();

                            ByteBuffer outBuffer = ByteBuffer.allocate(channelSamplesShortBuffer.capacity() * 2);

                            for (int i = 0; i < channelSamplesShortBuffer.capacity(); i++) {
                                short val = channelSamplesShortBuffer.get(i);
                                outBuffer.putShort(val);
                            }

                            /**
                             * We need this because soundLine.write ignores
                             * interruptions during writing.
                             */
                            try {
                                executor.submit(() -> {
                                    soundLine.write(outBuffer.array(), 0, outBuffer.capacity());
                                    outBuffer.clear();
                                }).get();
                            } catch (InterruptedException | ExecutionException ex) {
                                thAct.interrupt();
                                stopThread();
                                action = Action.None;
                                endOfFile();
                            }
                            
                        }

                        if(frame.timestamp / 1000L >= msAreaStop){
                            action = Action.Ready;
                            msAreaStart = 0L;
                            msAreaStop = 0L;
                        }
                    } catch (FrameGrabber.Exception ex) {
                        Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
        
        public void playStopAudio(){
            area = true;
            switch(action){
                case Ready -> action = Action.Play;
                case Play -> action = Action.Pause;
                case Pause -> action = Action.Play;
                case Stop -> action = Action.Play;
            }            
        }

        public Action getAction() {
            return action;
        }

        public void setAction(Action action) {
            this.action = action;
        }
        
        
    }
}
