/*
 * Copyright (C) 2020 util2
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.wingate.ygg.ui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import org.bytedeco.javacv.FrameGrabber;
import org.wingate.timelibrary.Time;
import org.wingate.ygg.MainFrame;
import org.wingate.ygg.io.video.VideoEvent;
import org.wingate.ygg.io.video.VideoListener;
import org.wingate.ygg.io.video.VideoPlayer;
import org.wingate.ygg.util.DrawColor;
import org.wingate.ygg.util.FFStuffs;
import org.wingate.ygg.util.FramesPanel;
import org.wingate.ygg.util.SubtitlesChoice;

/**
 *
 * @author util2
 */
public class IfrVideo extends javax.swing.JInternalFrame {
    
    private final VideoPlayer player = new VideoPlayer();
    private final VideoPanel vPane = new VideoPanel();
    private FramesPanel fp;
    
    private FFStuffs ffss = null;
    private IfrWave wave = null;
    
    private boolean media = false;
    
    private final SubtitlesChoice sChoice = new SubtitlesChoice();

    /**
     * Creates new form IfrVideo
     */
    public IfrVideo() {
        initComponents();
        init();
    }
    
    private void init(){
        wave = MainFrame.getAudioFrame();
        
        player.addVideoListener(new VideoListener() {
            @Override
            public void getImage(VideoEvent event) {
                Time ms = Time.fromMillisecondsTime(Math.round(event.getMilliseconds()));
                String frameNumber = Integer.toString(event.getFrameNumber());
                
                vPane.updateImage(event.getImage(), sChoice.getAtTime(ms));
                
                tfCurrentTime.setText(ms.toProgramExtendedTime());
                tfCurrentFrame.setText(frameNumber);
            }
        });
        
        panVideo.setLayout(new BorderLayout());
        panVideo.add(vPane, BorderLayout.CENTER);
    }

    public void setVideoPath(String videopath){
        //free();
        // Préparation de variables
        File video = new File(videopath);
        boolean darkUI = MainFrame.isDark();
        
        try {
            player.setVideo(video);
            media = video.exists();
        } catch (FrameGrabber.Exception ex) {
            return;
        }
        
        // Etude du signal
        ffss = FFStuffs.create(video);
        
        // Si audio faire waveform
        if(ffss.hasAudio()){
            wave.openAudio(video, ffss, darkUI);
        }
    }
    
    public void setSubtitlesFile(File subspath){
        sChoice.setSubtitlesFile(subspath);
    } 
    
    public void play(){
        if(player != null){
            player.playMedia();
        }
    }
    
    public void pause(){
        if(player != null){
            player.pauseMedia();
        }
    }
    
    public void stop(){
        if(player != null){
            player.stopMedia();
        }
    }
    
    public void playArea(Time start, Time stop){
        if(player != null){
            player.playMedia(start, stop);
        }
    }

    public boolean hasMedia() {
        return media;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panVideo = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panControls = new javax.swing.JPanel();
        tfStartFrame = new javax.swing.JTextField();
        tfEndFrame = new javax.swing.JTextField();
        tfDurationFrame = new javax.swing.JTextField();
        tfCurrentFrame = new javax.swing.JTextField();
        tfStartTime = new javax.swing.JTextField();
        tfEndTime = new javax.swing.JTextField();
        tfDurationTime = new javax.swing.JTextField();
        tfCurrentTime = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        btnPlay = new javax.swing.JButton();
        btnPause = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnBeforeStart = new javax.swing.JButton();
        btnBegin = new javax.swing.JButton();
        btnInside = new javax.swing.JButton();
        btnEnd = new javax.swing.JButton();
        btnAfter = new javax.swing.JButton();
        slideTime = new javax.swing.JSlider();
        panKeyFrames = new javax.swing.JPanel();

        setMaximizable(true);
        setResizable(true);
        setTitle("Video");

        panVideo.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout panVideoLayout = new javax.swing.GroupLayout(panVideo);
        panVideo.setLayout(panVideoLayout);
        panVideoLayout.setHorizontalGroup(
            panVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panVideoLayout.setVerticalGroup(
            panVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        tfStartFrame.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfStartFrame.setText("0");

        tfEndFrame.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfEndFrame.setText("0");

        tfDurationFrame.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfDurationFrame.setText("0");

        tfCurrentFrame.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCurrentFrame.setText("0");

        tfStartTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfStartTime.setText("00.00.00.000");

        tfEndTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfEndTime.setText("00.00.00.000");

        tfDurationTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfDurationTime.setText("00.00.00.000");

        tfCurrentTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCurrentTime.setText("00.00.00.000");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/32_timer_stuffs play.png"))); // NOI18N
        btnPlay.setText("Play");
        btnPlay.setFocusable(false);
        btnPlay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlay.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPlay);

        btnPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/32_timer_stuffs pause.png"))); // NOI18N
        btnPause.setText("Pause");
        btnPause.setFocusable(false);
        btnPause.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPause.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauseActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPause);

        btnStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/32_timer_stuffs stop.png"))); // NOI18N
        btnStop.setText("Stop");
        btnStop.setFocusable(false);
        btnStop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnStop.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });
        jToolBar1.add(btnStop);
        jToolBar1.add(jSeparator1);

        btnBeforeStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/32_timer_stuffs play out 01.png"))); // NOI18N
        btnBeforeStart.setText("Before");
        btnBeforeStart.setFocusable(false);
        btnBeforeStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBeforeStart.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBeforeStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeforeStartActionPerformed(evt);
            }
        });
        jToolBar1.add(btnBeforeStart);

        btnBegin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/32_timer_stuffs play in 01.png"))); // NOI18N
        btnBegin.setText("Begin");
        btnBegin.setFocusable(false);
        btnBegin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBegin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBegin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeginActionPerformed(evt);
            }
        });
        jToolBar1.add(btnBegin);

        btnInside.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/32_timer_stuffs in.png"))); // NOI18N
        btnInside.setText("At time");
        btnInside.setFocusable(false);
        btnInside.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInside.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnInside.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsideActionPerformed(evt);
            }
        });
        jToolBar1.add(btnInside);

        btnEnd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/32_timer_stuffs play in 02.png"))); // NOI18N
        btnEnd.setText("End");
        btnEnd.setFocusable(false);
        btnEnd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEnd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEnd);

        btnAfter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/32_timer_stuffs play out 02.png"))); // NOI18N
        btnAfter.setText("After");
        btnAfter.setFocusable(false);
        btnAfter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAfter.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAfter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfterActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAfter);

        javax.swing.GroupLayout panControlsLayout = new javax.swing.GroupLayout(panControls);
        panControls.setLayout(panControlsLayout);
        panControlsLayout.setHorizontalGroup(
            panControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panControlsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slideTime, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panControlsLayout.createSequentialGroup()
                        .addComponent(tfStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDurationTime, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCurrentTime, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panControlsLayout.createSequentialGroup()
                        .addComponent(tfStartFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfEndFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDurationFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCurrentFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
        );
        panControlsLayout.setVerticalGroup(
            panControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panControlsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panControlsLayout.createSequentialGroup()
                        .addComponent(slideTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDurationTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCurrentTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfStartFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfEndFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDurationFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCurrentFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", panControls);

        javax.swing.GroupLayout panKeyFramesLayout = new javax.swing.GroupLayout(panKeyFrames);
        panKeyFrames.setLayout(panKeyFramesLayout);
        panKeyFramesLayout.setHorizontalGroup(
            panKeyFramesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panKeyFramesLayout.setVerticalGroup(
            panKeyFramesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panVideo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1)
                    .addComponent(panKeyFrames, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panVideo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panKeyFrames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        play();
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseActionPerformed
        pause();
    }//GEN-LAST:event_btnPauseActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        stop();
    }//GEN-LAST:event_btnStopActionPerformed

    private void btnBeforeStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeforeStartActionPerformed
        Time end = fp.getAreaStartTime();
        Time start = Time.substract(end, Time.create(500L));
        playArea(start, end);
    }//GEN-LAST:event_btnBeforeStartActionPerformed

    private void btnBeginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeginActionPerformed
        Time start = fp.getAreaStartTime();
        Time end = Time.addition(start, Time.create(500L));
        playArea(start, end);
    }//GEN-LAST:event_btnBeginActionPerformed

    private void btnInsideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsideActionPerformed
        Time start = fp.getAreaStartTime();
        Time end = fp.getAreaEndTime();
        playArea(start, end);
    }//GEN-LAST:event_btnInsideActionPerformed

    private void btnEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndActionPerformed
        Time end = fp.getAreaEndTime();
        Time start = Time.substract(end, Time.create(500L));
        playArea(start, end);
    }//GEN-LAST:event_btnEndActionPerformed

    private void btnAfterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfterActionPerformed
        Time start = fp.getAreaEndTime();
        Time end = Time.addition(start, Time.create(500L));
        playArea(start, end);
    }//GEN-LAST:event_btnAfterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfter;
    private javax.swing.JButton btnBeforeStart;
    private javax.swing.JButton btnBegin;
    private javax.swing.JButton btnEnd;
    private javax.swing.JButton btnInside;
    private javax.swing.JButton btnPause;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnStop;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel panControls;
    private javax.swing.JPanel panKeyFrames;
    private javax.swing.JPanel panVideo;
    private javax.swing.JSlider slideTime;
    private javax.swing.JTextField tfCurrentFrame;
    private javax.swing.JTextField tfCurrentTime;
    private javax.swing.JTextField tfDurationFrame;
    private javax.swing.JTextField tfDurationTime;
    private javax.swing.JTextField tfEndFrame;
    private javax.swing.JTextField tfEndTime;
    private javax.swing.JTextField tfStartFrame;
    private javax.swing.JTextField tfStartTime;
    // End of variables declaration//GEN-END:variables

    class VideoPanel extends javax.swing.JPanel {

        private BufferedImage img = null;
        private BufferedImage sub = null; // For subtitles
        private boolean darkMode = false;
        
        public VideoPanel() {            
            init();
        }
        
        private void init(){
            setDoubleBuffered(true);
        }

        public void setDarkMode(boolean darkMode) {
            this.darkMode = darkMode;
        }
        
        public void updateImage(BufferedImage img, BufferedImage sub){
            this.img = img;
            this.sub = sub;
            repaint();
        }
        
        public void updateImage(BufferedImage img){
            this.img = img;
            repaint();
        }

        @Override
        public void paint(Graphics g) {
            super.paint(g);
            
            if(img != null){
                g.setColor(darkMode == true ? Color.gray : DrawColor.alice_blue.getColor());
                g.fillRect(0, 0, getWidth(), getHeight());

                Dimension dim = getScaledDimension(
                        new Dimension(img.getWidth(), img.getHeight()), 
                        new Dimension(getWidth(), getHeight())
                );

                int x = (getWidth() - dim.width) / 2;
                int y = (getHeight() - dim.height) / 2;
                g.drawImage(img, x, y, dim.width, dim.height, null);
            }
            
            if(sub != null){
                Dimension dim = getScaledDimension(
                        new Dimension(sub.getWidth(), sub.getHeight()), 
                        new Dimension(getWidth(), getHeight())
                );

                int x = (getWidth() - dim.width) / 2;
                int y = (getHeight() - dim.height) / 2;
                g.drawImage(sub, x, y, dim.width, dim.height, null);
            }
        }
        
        private Dimension getScaledDimension(Dimension imgSize, Dimension boundary) {

            int original_width = imgSize.width;
            int original_height = imgSize.height;
            int bound_width = boundary.width;
            int bound_height = boundary.height;
            int new_width = original_width;
            int new_height = original_height;

            // first check if we need to scale width
            if (original_width > bound_width) {
                //scale width to fit
                new_width = bound_width;
                //scale height to maintain aspect ratio
                new_height = (new_width * original_height) / original_width;
            }

            // then check if we need to scale even with the new height
            if (new_height > bound_height) {
                //scale height to fit instead
                new_height = bound_height;
                //scale width to maintain aspect ratio
                new_width = (new_height * original_width) / original_height;
            }

            return new Dimension(new_width, new_height);
        }
        
    }
}
