/*
 * Copyright (C) 2021 util2
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.wingate.ygg.ui;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.text.BadLocationException;
import org.wingate.timelibrary.Time;
import org.wingate.ygg.MainFrame;
import org.wingate.ygg.p2p.Client;
import org.wingate.ygg.p2p.InSubsMessage;
import org.wingate.ygg.subs.ass.AssEvent;
import org.wingate.ygg.ui.synctable.SelectedFormat;
import org.wingate.ygg.util.Clipboard;
import org.wingate.ygglock.YggLock;

/**
 *
 * @author util2
 */
public class PRChatSeeDialog extends javax.swing.JDialog {
    
    public enum Type {
        Unknown, Proposal, Request;
    }
    
    private AssEvent assEvent = null;

    public PRChatSeeDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }
    
    private void init(){
        setSize(600, 200);
        setLocationRelativeTo(null);
    }
    
    public void showDialog(Object obj, Type type){
        if(obj instanceof AssEvent){
            AssEvent ev = (AssEvent)obj;
            assEvent = ev;
            tfStart.setText(ev.getStartTime().toASSTime());
            tfEnd.setText(ev.getEndTime().toASSTime());
            tpPR.setText(ev.getText());
            switch(type){
                case Proposal -> { lblPR.setText("Proposal"); }
                case Request -> { lblPR.setText("Request"); }
            }
            setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        mnuCopy = new javax.swing.JMenuItem();
        mnuPaste = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuBefore = new javax.swing.JMenuItem();
        mnuAfter = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuSendProposal = new javax.swing.JMenuItem();
        mnuSendRequest = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfStart = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfEnd = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tpPR = new javax.swing.JTextPane();
        lblPR = new javax.swing.JLabel();

        mnuCopy.setText("Copy");
        mnuCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCopyActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnuCopy);

        mnuPaste.setText("Paste");
        mnuPaste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPasteActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnuPaste);
        jPopupMenu1.add(jSeparator1);

        mnuBefore.setText("Add before");
        mnuBefore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBeforeActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnuBefore);

        mnuAfter.setText("Add after");
        mnuAfter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAfterActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnuAfter);
        jPopupMenu1.add(jSeparator2);

        mnuSendProposal.setText("Send proposal");
        mnuSendProposal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSendProposalActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnuSendProposal);

        mnuSendRequest.setText("Send request");
        mnuSendRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSendRequestActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnuSendRequest);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Start at :");
        jPanel2.add(jLabel1, java.awt.BorderLayout.NORTH);

        tfStart.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfStart.setText("0.00.00.000");
        jPanel2.add(tfStart, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("End at :");
        jPanel3.add(jLabel2, java.awt.BorderLayout.NORTH);

        tfEnd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfEnd.setText("0.00.00.000");
        jPanel3.add(tfEnd, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tpPR.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(tpPR);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        lblPR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPR.setText("PR");
        getContentPane().add(lblPR, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCopyActionPerformed
        Clipboard.CCopy(tpPR.getSelectedText());
    }//GEN-LAST:event_mnuCopyActionPerformed

    private void mnuPasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPasteActionPerformed
        try {
            tpPR.getDocument().insertString(tpPR.getCaretPosition(), Clipboard.CPaste(), null);
        } catch (BadLocationException ex) {
            Logger.getLogger(PRChatSeeDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuPasteActionPerformed

    private void mnuBeforeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBeforeActionPerformed
        if(MainFrame.getTableFrame() == null) return;
        if(MainFrame.getTableFrame().getFormat() == SelectedFormat.ASS){
            //===---
            IfrTable table = MainFrame.getTableFrame();
            //===---
            AssEvent nv = assEvent;
            nv.setStartTime(Time.create(tfStart.getText()));
            nv.setEndTime(Time.create(tfEnd.getText()));
            nv.setText(tpPR.getText());
            if(table.getTable().getSelectedRow() != -1){
                table.getLastAssSynchroTable().getAssTableModel().insertOneAt(nv, table.getTable().getSelectedRow());
                table.getLastAssSynchroTable().getTable().updateUI();
            }
        }
    }//GEN-LAST:event_mnuBeforeActionPerformed

    private void mnuAfterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAfterActionPerformed
        if(MainFrame.getTableFrame() == null) return;
        if(MainFrame.getTableFrame().getFormat() == SelectedFormat.ASS){
            //===---
            IfrTable table = MainFrame.getTableFrame();
            //===---
            AssEvent nv = assEvent;
            nv.setStartTime(Time.create(tfStart.getText()));
            nv.setEndTime(Time.create(tfEnd.getText()));
            nv.setText(tpPR.getText());
            if(table.getTable().getSelectedRow() != -1){
                if(table.getTable().getRowCount() - 1 == table.getTable().getSelectedRow()){
                    // We are at last event
                    table.getLastAssSynchroTable().getAssTableModel().insertOne(nv);
                }else{
                    // We are inside the events cosmos
                    table.getLastAssSynchroTable().getAssTableModel().insertOneAt(nv, table.getTable().getSelectedRow() + 1);
                }
                table.getLastAssSynchroTable().getTable().updateUI();
            }
        }
    }//GEN-LAST:event_mnuAfterActionPerformed

    private void mnuSendProposalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSendProposalActionPerformed
        PRDialog pr = new PRDialog(new JFrame(), true);
        pr.showDialog(MainFrame.getCryptObjs());

        List<InSubsMessage> list = new ArrayList<>();
        AssEvent nv = assEvent;
        nv.setLineType(AssEvent.LineType.Proposal);
        nv.setStartTime(Time.create(tfStart.getText()));
        nv.setEndTime(Time.create(tfEnd.getText()));
        nv.setText(tpPR.getText());
        list.add(new InSubsMessage(InSubsMessage.InSubsType.Proposal, AssEvent.getAssEventLine(nv)));

        if(list.isEmpty() == false && pr.getDialogResult() == PRDialog.DialogResult.OK){
            for(YggLock.CryptObj co : pr.getSelection()){
                Client.sendProposalMessage(co, list);
            }            
        }
    }//GEN-LAST:event_mnuSendProposalActionPerformed

    private void mnuSendRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSendRequestActionPerformed
        PRDialog pr = new PRDialog(new JFrame(), true);
        pr.showDialog(MainFrame.getCryptObjs());

        List<InSubsMessage> list = new ArrayList<>();
        AssEvent nv = assEvent;
        nv.setLineType(AssEvent.LineType.Request);
        nv.setStartTime(Time.create(tfStart.getText()));
        nv.setEndTime(Time.create(tfEnd.getText()));
        nv.setText(tpPR.getText());
        list.add(new InSubsMessage(InSubsMessage.InSubsType.Request, AssEvent.getAssEventLine(nv)));

        if(list.isEmpty() == false && pr.getDialogResult() == PRDialog.DialogResult.OK){
            for(YggLock.CryptObj co : pr.getSelection()){
                Client.sendRequestMessage(co, list);
            }            
        }
    }//GEN-LAST:event_mnuSendRequestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRChatSeeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRChatSeeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRChatSeeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRChatSeeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PRChatSeeDialog dialog = new PRChatSeeDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lblPR;
    private javax.swing.JMenuItem mnuAfter;
    private javax.swing.JMenuItem mnuBefore;
    private javax.swing.JMenuItem mnuCopy;
    private javax.swing.JMenuItem mnuPaste;
    private javax.swing.JMenuItem mnuSendProposal;
    private javax.swing.JMenuItem mnuSendRequest;
    private javax.swing.JTextField tfEnd;
    private javax.swing.JTextField tfStart;
    private javax.swing.JTextPane tpPR;
    // End of variables declaration//GEN-END:variables
}
