/*
 * Copyright (C) 2021 util2
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.wingate.ygg.ui;

/**
 *
 * @author util2
 */
public class SubsChoiceDialog extends javax.swing.JDialog {
    
    public enum DialogResult {
        None, Cancel, OK;
    }
    
    public enum Choice {
        ASS, SSB, SRT, WebVTT, VES;
    }
    
    private Choice choice = Choice.ASS;
    private DialogResult dialogResult = DialogResult.None;
    private java.awt.Frame parent = null;

    public SubsChoiceDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.parent = parent;
    }
    
    public void showDialog(){
        setPreferredSize(new java.awt.Dimension(200, 1000));
        setLocationRelativeTo(parent);
        setVisible(true);
    }

    public DialogResult getDialogResult() {
        return dialogResult;
    }

    public Choice getChoice() {
        return choice;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgChoice = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        tbASSA = new javax.swing.JToggleButton();
        tbSSB = new javax.swing.JToggleButton();
        tbSRT = new javax.swing.JToggleButton();
        tbWebVTT = new javax.swing.JToggleButton();
        tbVES = new javax.swing.JToggleButton();
        btnCancel = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        bgChoice.add(tbASSA);
        tbASSA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Aegisub min.png"))); // NOI18N
        tbASSA.setSelected(true);
        tbASSA.setText("ASS");
        tbASSA.setFocusable(false);
        tbASSA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbASSA.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbASSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbASSAActionPerformed(evt);
            }
        });
        jToolBar1.add(tbASSA);

        bgChoice.add(tbSSB);
        tbSSB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SubStation Beta min.png"))); // NOI18N
        tbSSB.setText("SSB");
        tbSSB.setFocusable(false);
        tbSSB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbSSB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbSSB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbSSBActionPerformed(evt);
            }
        });
        jToolBar1.add(tbSSB);

        bgChoice.add(tbSRT);
        tbSRT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/YGG_Icone min.png"))); // NOI18N
        tbSRT.setText("SRT");
        tbSRT.setEnabled(false);
        tbSRT.setFocusable(false);
        tbSRT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbSRT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbSRT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbSRTActionPerformed(evt);
            }
        });
        jToolBar1.add(tbSRT);

        bgChoice.add(tbWebVTT);
        tbWebVTT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/YGG_Icone min.png"))); // NOI18N
        tbWebVTT.setText("WebVTT");
        tbWebVTT.setEnabled(false);
        tbWebVTT.setFocusable(false);
        tbWebVTT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbWebVTT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbWebVTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbWebVTTActionPerformed(evt);
            }
        });
        jToolBar1.add(tbWebVTT);

        bgChoice.add(tbVES);
        tbVES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/YGG_Icone min.png"))); // NOI18N
        tbVES.setText("VES");
        tbVES.setEnabled(false);
        tbVES.setFocusable(false);
        tbVES.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbVES.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbVES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbVESActionPerformed(evt);
            }
        });
        jToolBar1.add(tbVES);

        btnCancel.setForeground(new java.awt.Color(255, 0, 0));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnOK.setForeground(new java.awt.Color(0, 153, 51));
        btnOK.setText("New");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOK)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnOK))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        dialogResult = DialogResult.OK;
        dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dialogResult = DialogResult.Cancel;
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void tbASSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbASSAActionPerformed
        choice = Choice.ASS;
    }//GEN-LAST:event_tbASSAActionPerformed

    private void tbSSBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbSSBActionPerformed
        choice = Choice.SSB;
    }//GEN-LAST:event_tbSSBActionPerformed

    private void tbSRTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbSRTActionPerformed
        choice = Choice.SRT;
    }//GEN-LAST:event_tbSRTActionPerformed

    private void tbWebVTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbWebVTTActionPerformed
        choice = Choice.WebVTT;
    }//GEN-LAST:event_tbWebVTTActionPerformed

    private void tbVESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbVESActionPerformed
        choice = Choice.VES;
    }//GEN-LAST:event_tbVESActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubsChoiceDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubsChoiceDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubsChoiceDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubsChoiceDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SubsChoiceDialog dialog = new SubsChoiceDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgChoice;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToggleButton tbASSA;
    private javax.swing.JToggleButton tbSRT;
    private javax.swing.JToggleButton tbSSB;
    private javax.swing.JToggleButton tbVES;
    private javax.swing.JToggleButton tbWebVTT;
    // End of variables declaration//GEN-END:variables
}
