/*
 * Copyright (C) 2020 util2
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package ygg;

import java.io.File;
import java.util.Locale;
import ygg.io.language.ISO_3166;
import ygg.io.language.Language;
import ygg.ui.IfrTable;
import ygg.ui.IfrTableLink;
import ygg.ui.IfrVideo;
import ygg.ui.IfrWave;

/**
 *
 * @author util2
 */
public class MainFrame extends javax.swing.JFrame {
    
    // Temp folder
    private static final String TEMP_FOLDER = "tempFolder";

    // Language (loading from properties of each component)
    static ISO_3166 wantedIso = ISO_3166.getISO_3166(Locale.getDefault().getISO3Country());
    static Language chosen = new Language();
    
    private static boolean darkUI = false;
    
    // Timing components
    private static final IfrTable table = new IfrTable();
    private static final IfrVideo video = new IfrVideo();
    private static final IfrWave wave = new IfrWave();
    private static final IfrTableLink tableLink = new IfrTableLink();

    public MainFrame(boolean dark) {
        initComponents();
        darkUI = dark;
        init();
    }
    
    private void init(){
        File temp_folder = new File(TEMP_FOLDER);
        temp_folder.mkdir();
        temp_folder.deleteOnExit();
        
        setSize(1880, 1058);
        setLocationRelativeTo(null);
        
        tabbedApp.setSelectedIndex(2); // Timing
        
        //----------------------------------------------------------------------
        // Timing configuration
        //----------------------------------------------------------------------
        deskTiming.add(table);
        table.setSize(1864, 300);
        table.setLocation(0, 615);
        table.setVisible(true);
        deskTiming.add(video);
        video.setSize(1864/2, 615);
        video.setLocation(0, 0);
        video.setVisible(true);
        deskTiming.add(wave);
        wave.setSize(1864/2, 300);
        wave.setLocation(1864/2, 0);
        wave.setVisible(true);
        deskTiming.add(tableLink);
        tableLink.setSize(1864/2, 315);
        tableLink.setLocation(1864/2, 300);
        tableLink.setVisible(true);
        //------------------------------------------------------- TIMING END ---
    }
    
    public void setDarkUI(boolean darkUI) {
        MainFrame.darkUI = darkUI;
    }
    
    public static boolean isDark(){
        return darkUI;
    }
    
    public static Language getLanguage(){
        return chosen;
    }
    
    public static ISO_3166 getISO(){
        return wantedIso;
    }
    
    public static String getTempFolder(){
        return TEMP_FOLDER;
    }
    
    //<editor-fold defaultstate="collapsed" desc="Internal Frames">
    
    public static IfrVideo getVideoFrame(){
        return video;
    }
    
    public static IfrWave getAudioFrame(){
        return wave;
    }
    
    public static IfrTable getTableFrame(){
        return table;
    }
    
    public static IfrTableLink getTableLinkFrame(){
        return tableLink;
    }
    //</editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedApp = new javax.swing.JTabbedPane();
        panChat = new javax.swing.JPanel();
        panPTP = new javax.swing.JPanel();
        panTiming = new javax.swing.JPanel();
        deskTiming = new javax.swing.JDesktopPane();
        tfLastChatMessage = new javax.swing.JTextField();
        pbDownload = new javax.swing.JProgressBar();
        mbTop = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Yggdrasil 2020-11 - \"Happy go ducky\"");

        javax.swing.GroupLayout panChatLayout = new javax.swing.GroupLayout(panChat);
        panChat.setLayout(panChatLayout);
        panChatLayout.setHorizontalGroup(
            panChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        panChatLayout.setVerticalGroup(
            panChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );

        tabbedApp.addTab("Chat", panChat);

        javax.swing.GroupLayout panPTPLayout = new javax.swing.GroupLayout(panPTP);
        panPTP.setLayout(panPTPLayout);
        panPTPLayout.setHorizontalGroup(
            panPTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        panPTPLayout.setVerticalGroup(
            panPTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );

        tabbedApp.addTab("Files", panPTP);

        panTiming.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout deskTimingLayout = new javax.swing.GroupLayout(deskTiming);
        deskTiming.setLayout(deskTimingLayout);
        deskTimingLayout.setHorizontalGroup(
            deskTimingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        deskTimingLayout.setVerticalGroup(
            deskTimingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );

        panTiming.add(deskTiming, java.awt.BorderLayout.CENTER);

        tabbedApp.addTab("Timing", panTiming);

        jMenu1.setText("File");
        mbTop.add(jMenu1);

        jMenu2.setText("Edit");
        mbTop.add(jMenu2);

        setJMenuBar(mbTop);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedApp)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pbDownload, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfLastChatMessage))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedApp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfLastChatMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbDownload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainFrame(false).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane deskTiming;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar mbTop;
    private javax.swing.JPanel panChat;
    private javax.swing.JPanel panPTP;
    private javax.swing.JPanel panTiming;
    private javax.swing.JProgressBar pbDownload;
    private javax.swing.JTabbedPane tabbedApp;
    private javax.swing.JTextField tfLastChatMessage;
    // End of variables declaration//GEN-END:variables
}
