/*
 * Copyright (C) 2020 util2
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package ygg.ui;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import org.wingate.timelibrary.Time;
import replica.event.ChatTextEvent;
import replica.event.ReceiverListener;
import replica.ygg.PeerClient;
import replica.ygg.PeerHandler;
import ygg.io.YggConf;
import ygg.io.YggSystem;

/**
 *
 * @author util2
 */
public class IfrChat extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form IfrChat
     */
    public IfrChat() {
        initComponents();
        init();
    }
    
    private void init(){
        PeerHandler.addReceiverListener(new ReceiverListener() {
            @Override
            public void getChatText(ChatTextEvent event) {
                Calendar cal = Calendar.getInstance();
                Time t = Time.create(cal.getTimeInMillis());
                String text = t.toProgramExtendedTime() + " " + event.getMessage() + "\n";
                Document doc = tpChat.getDocument();
                try {
                    doc.insertString(doc.getEndPosition().getOffset(), text, null);
                } catch (BadLocationException ex) {
                    Logger.getLogger(IfrChat.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfChatMessage = new javax.swing.JTextField();
        btnSendMessage = new javax.swing.JButton();
        btnAddSmiley = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tpChat = new javax.swing.JTextPane();
        tfSurname = new org.wingate.placeholdertextfield.PlaceholderTextField();
        tfTeam = new org.wingate.placeholdertextfield.PlaceholderTextField();
        jCheckBox1 = new javax.swing.JCheckBox();

        tfChatMessage.setText("Demo :)");

        btnSendMessage.setText("Send");
        btnSendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendMessageActionPerformed(evt);
            }
        });

        btnAddSmiley.setText("Emojis");
        btnAddSmiley.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSmileyActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setViewportView(tpChat);

        tfSurname.setPlaceholder("Surname");

        tfTeam.setPlaceholder("Team name");

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Online");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddSmiley)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSendMessage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfChatMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfChatMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddSmiley)
                    .addComponent(btnSendMessage)
                    .addComponent(tfSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddSmileyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSmileyActionPerformed
        // TODO add your handling code here:
        tpChat.setText("1");
    }//GEN-LAST:event_btnAddSmileyActionPerformed

    private void btnSendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendMessageActionPerformed
        String surname = tfSurname.getText().isEmpty() ? "Newbie" : tfSurname.getText();
        String team = tfTeam.getText().isEmpty() ? "Battle Royale" : tfTeam.getText();
        String ip = jCheckBox1.isSelected() ? YggSystem.resolveRemoteIPv4() : YggSystem.resolveLocalIPv4();
        try {
            PeerClient.replica(YggConf.getIpReplica(), team, ip, surname);
            PeerClient.chatTextToReplica(YggConf.getIpReplica(), team, surname + " -> " + tfChatMessage.getText());
        } catch (IOException ex) {
            Logger.getLogger(IfrChat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSendMessageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSmiley;
    private javax.swing.JButton btnSendMessage;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfChatMessage;
    private org.wingate.placeholdertextfield.PlaceholderTextField tfSurname;
    private org.wingate.placeholdertextfield.PlaceholderTextField tfTeam;
    private javax.swing.JTextPane tpChat;
    // End of variables declaration//GEN-END:variables
}
