/*
 * Copyright (C) 2020 util2
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.wingate.ygg.ifrm;

import java.awt.BorderLayout;
import java.awt.Point;
import java.io.File;
import org.wingate.ygg.MainFrame;
import org.wingate.ygg.ass.Event;
import org.wingate.ygg.base.AVStudio;
import org.wingate.ygg.karaoke.SyllableCollection;
import org.wingate.ygg.ui.AudioWave;
import org.wingate.ygg.util.FFStuffs;
import org.wingate.ygg.util.Time;

/**
 *
 * @author util2
 */
public class FrmWave extends javax.swing.JInternalFrame {
    
    private final AVStudio studio;

    FFStuffs ffss;
    AudioWave aw = null;
    
    SyllableCollection currentKaraoke = null;
    
    /**
     * Creates new form FrmWave
     * @param studio
     */
    public FrmWave(AVStudio studio) {
        initComponents();
        this.studio = studio;
        init();
    }
    
    private void init(){
        toggleEnableKara.setSelected(false);
        btnPlayBeforeStartSyllable.setEnabled(toggleEnableKara.isSelected());
        btnPlayAfterStartSyllable.setEnabled(toggleEnableKara.isSelected());
        btnPlayAreaSyllable.setEnabled(toggleEnableKara.isSelected());
        btnPlayBeforeEndSyllable.setEnabled(toggleEnableKara.isSelected());
        btnPlayAfterEndSyllable.setEnabled(toggleEnableKara.isSelected());
        btnPreviousSyllable.setEnabled(toggleEnableKara.isSelected());
        btnNextSyllable.setEnabled(toggleEnableKara.isSelected());
    }
    
    public void setFile(File f){
        aw = AudioWave.create(f, studio.getFfss(), studio.isDark());
        
        studio.setAw(aw);
        
        paneEmbedWave.setLayout(new BorderLayout());
        paneEmbedWave.add(aw, BorderLayout.CENTER);
        aw.setWaveHeight(250);
        aw.updateDisplayWithOffset(0, Time.create(0L), Time.create(0L));
        
        updateUI();
    }
    
    public void displayEventTime(Event ev){
        int startFrame = Time.getFrame(ev.getStartTime(), studio.getFfss().getFps());
        int endFrame = Time.getFrame(ev.getEndTime(), studio.getFfss().getFps());
        
        int startSamples = aw.getSamplesFromFrame(startFrame);
        int endSamples = aw.getSamplesFromFrame(endFrame);
        
        Point start = new Point(Math.round(startSamples / aw.getSamplesPerPixel()), 0);
        Point stop = new Point(Math.round(endSamples / aw.getSamplesPerPixel()), 0);
        
        aw.getAudioWavePanel().updatePoint(start, stop);
        
        currentKaraoke = SyllableCollection.create(ev, MainFrame.getKaraokeLanguage());        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnPlayWave = new javax.swing.JButton();
        btnPauseWave = new javax.swing.JButton();
        btnStopWave = new javax.swing.JButton();
        sepAudio01 = new javax.swing.JToolBar.Separator();
        btnPlayBeforeStart = new javax.swing.JButton();
        btnPlayAfterStart = new javax.swing.JButton();
        btnPlayArea = new javax.swing.JButton();
        btnPlayBeforeEnd = new javax.swing.JButton();
        btnPlayAfterEnd = new javax.swing.JButton();
        sepAudio02 = new javax.swing.JToolBar.Separator();
        btnModifyAreaGot = new javax.swing.JButton();
        btnAcceptGot = new javax.swing.JButton();
        sepAudio03 = new javax.swing.JToolBar.Separator();
        toggleEnableKara = new javax.swing.JToggleButton();
        btnPlayBeforeStartSyllable = new javax.swing.JButton();
        btnPlayAfterStartSyllable = new javax.swing.JButton();
        btnPlayAreaSyllable = new javax.swing.JButton();
        btnPlayBeforeEndSyllable = new javax.swing.JButton();
        btnPlayAfterEndSyllable = new javax.swing.JButton();
        btnPreviousSyllable = new javax.swing.JButton();
        btnNextSyllable = new javax.swing.JButton();
        sepAudio04 = new javax.swing.JToolBar.Separator();
        paneEmbedWave = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        jSlider2 = new javax.swing.JSlider();
        jSlider3 = new javax.swing.JSlider();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Audio Swing");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnPlayWave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/32_timer_stuffs play.png"))); // NOI18N
        btnPlayWave.setText("Play");
        btnPlayWave.setToolTipText("Play audio");
        btnPlayWave.setFocusable(false);
        btnPlayWave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlayWave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPlayWave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayWaveActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPlayWave);

        btnPauseWave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/32_timer_stuffs pause.png"))); // NOI18N
        btnPauseWave.setText("Pause");
        btnPauseWave.setToolTipText("Pause audio");
        btnPauseWave.setFocusable(false);
        btnPauseWave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPauseWave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPauseWave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauseWaveActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPauseWave);

        btnStopWave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/32_timer_stuffs stop.png"))); // NOI18N
        btnStopWave.setText("Stop");
        btnStopWave.setToolTipText("Stop audio");
        btnStopWave.setFocusable(false);
        btnStopWave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnStopWave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnStopWave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopWaveActionPerformed(evt);
            }
        });
        jToolBar1.add(btnStopWave);
        jToolBar1.add(sepAudio01);

        btnPlayBeforeStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/32_timer_stuffs play out 01.png"))); // NOI18N
        btnPlayBeforeStart.setText("Before");
        btnPlayBeforeStart.setToolTipText("Play before start of the event");
        btnPlayBeforeStart.setFocusable(false);
        btnPlayBeforeStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlayBeforeStart.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPlayBeforeStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayBeforeStartActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPlayBeforeStart);

        btnPlayAfterStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/32_timer_stuffs play in 01.png"))); // NOI18N
        btnPlayAfterStart.setText("Begin");
        btnPlayAfterStart.setToolTipText("Play after start of the event");
        btnPlayAfterStart.setFocusable(false);
        btnPlayAfterStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlayAfterStart.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPlayAfterStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayAfterStartActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPlayAfterStart);

        btnPlayArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/32_timer_stuffs in.png"))); // NOI18N
        btnPlayArea.setText("Area");
        btnPlayArea.setToolTipText("Playing event");
        btnPlayArea.setFocusable(false);
        btnPlayArea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlayArea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPlayArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayAreaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPlayArea);

        btnPlayBeforeEnd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/32_timer_stuffs play in 02.png"))); // NOI18N
        btnPlayBeforeEnd.setText("End");
        btnPlayBeforeEnd.setToolTipText("Play before end of the event");
        btnPlayBeforeEnd.setFocusable(false);
        btnPlayBeforeEnd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlayBeforeEnd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPlayBeforeEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayBeforeEndActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPlayBeforeEnd);

        btnPlayAfterEnd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/32_timer_stuffs play out 02.png"))); // NOI18N
        btnPlayAfterEnd.setText("After");
        btnPlayAfterEnd.setToolTipText("Play after end of the event");
        btnPlayAfterEnd.setFocusable(false);
        btnPlayAfterEnd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlayAfterEnd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPlayAfterEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayAfterEndActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPlayAfterEnd);
        jToolBar1.add(sepAudio02);

        btnModifyAreaGot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/32 modify.png"))); // NOI18N
        btnModifyAreaGot.setText("Modify");
        btnModifyAreaGot.setToolTipText("Accept area modification");
        btnModifyAreaGot.setFocusable(false);
        btnModifyAreaGot.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModifyAreaGot.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModifyAreaGot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyAreaGotActionPerformed(evt);
            }
        });
        jToolBar1.add(btnModifyAreaGot);

        btnAcceptGot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/32 accept.png"))); // NOI18N
        btnAcceptGot.setText("Accept");
        btnAcceptGot.setToolTipText("Accept area");
        btnAcceptGot.setFocusable(false);
        btnAcceptGot.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAcceptGot.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAcceptGot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptGotActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAcceptGot);
        jToolBar1.add(sepAudio03);

        toggleEnableKara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/40 sync.png"))); // NOI18N
        toggleEnableKara.setText("Karaoke");
        toggleEnableKara.setToolTipText("Enable karaoke or disable");
        toggleEnableKara.setFocusable(false);
        toggleEnableKara.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toggleEnableKara.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toggleEnableKara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleEnableKaraActionPerformed(evt);
            }
        });
        jToolBar1.add(toggleEnableKara);

        btnPlayBeforeStartSyllable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/40 sync before start.png"))); // NOI18N
        btnPlayBeforeStartSyllable.setText("Before");
        btnPlayBeforeStartSyllable.setToolTipText("Play before the start of the syllable");
        btnPlayBeforeStartSyllable.setFocusable(false);
        btnPlayBeforeStartSyllable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlayBeforeStartSyllable.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPlayBeforeStartSyllable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayBeforeStartSyllableActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPlayBeforeStartSyllable);

        btnPlayAfterStartSyllable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/40 sync after start.png"))); // NOI18N
        btnPlayAfterStartSyllable.setText("Begin");
        btnPlayAfterStartSyllable.setToolTipText("Play after the start of the syllable");
        btnPlayAfterStartSyllable.setFocusable(false);
        btnPlayAfterStartSyllable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlayAfterStartSyllable.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPlayAfterStartSyllable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayAfterStartSyllableActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPlayAfterStartSyllable);

        btnPlayAreaSyllable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/40 sync in.png"))); // NOI18N
        btnPlayAreaSyllable.setText("Area");
        btnPlayAreaSyllable.setToolTipText("Play the area of the syllable");
        btnPlayAreaSyllable.setFocusable(false);
        btnPlayAreaSyllable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlayAreaSyllable.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPlayAreaSyllable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayAreaSyllableActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPlayAreaSyllable);

        btnPlayBeforeEndSyllable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/40 sync before end.png"))); // NOI18N
        btnPlayBeforeEndSyllable.setText("End");
        btnPlayBeforeEndSyllable.setToolTipText("Play before the end of the syllable");
        btnPlayBeforeEndSyllable.setFocusable(false);
        btnPlayBeforeEndSyllable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlayBeforeEndSyllable.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPlayBeforeEndSyllable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayBeforeEndSyllableActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPlayBeforeEndSyllable);

        btnPlayAfterEndSyllable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/40 sync after end.png"))); // NOI18N
        btnPlayAfterEndSyllable.setText("After");
        btnPlayAfterEndSyllable.setToolTipText("Play after the end of the syllable");
        btnPlayAfterEndSyllable.setFocusable(false);
        btnPlayAfterEndSyllable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlayAfterEndSyllable.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPlayAfterEndSyllable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayAfterEndSyllableActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPlayAfterEndSyllable);

        btnPreviousSyllable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/40 sync prev.png"))); // NOI18N
        btnPreviousSyllable.setText("Previous");
        btnPreviousSyllable.setToolTipText("Previous syllable if any");
        btnPreviousSyllable.setFocusable(false);
        btnPreviousSyllable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPreviousSyllable.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPreviousSyllable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousSyllableActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPreviousSyllable);

        btnNextSyllable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/40 sync next.png"))); // NOI18N
        btnNextSyllable.setText("Next");
        btnNextSyllable.setToolTipText("Next syllable if any");
        btnNextSyllable.setFocusable(false);
        btnNextSyllable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNextSyllable.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNextSyllable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextSyllableActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNextSyllable);
        jToolBar1.add(sepAudio04);

        paneEmbedWave.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout paneEmbedWaveLayout = new javax.swing.GroupLayout(paneEmbedWave);
        paneEmbedWave.setLayout(paneEmbedWaveLayout);
        paneEmbedWaveLayout.setHorizontalGroup(
            paneEmbedWaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        paneEmbedWaveLayout.setVerticalGroup(
            paneEmbedWaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider1.setToolTipText("");
        jSlider1.setValue(100);

        jSlider2.setOrientation(javax.swing.JSlider.VERTICAL);

        jSlider3.setOrientation(javax.swing.JSlider.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1129, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(paneEmbedWave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSlider3, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                    .addComponent(paneEmbedWave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSlider2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSlider1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toggleEnableKaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleEnableKaraActionPerformed
        btnPlayBeforeStartSyllable.setEnabled(toggleEnableKara.isSelected());
        btnPlayAfterStartSyllable.setEnabled(toggleEnableKara.isSelected());
        btnPlayAreaSyllable.setEnabled(toggleEnableKara.isSelected());
        btnPlayBeforeEndSyllable.setEnabled(toggleEnableKara.isSelected());
        btnPlayAfterEndSyllable.setEnabled(toggleEnableKara.isSelected());
        btnPreviousSyllable.setEnabled(toggleEnableKara.isSelected());
        btnNextSyllable.setEnabled(toggleEnableKara.isSelected());
        
        aw.getAudioWavePanel().setEnableKaraoke(toggleEnableKara.isSelected(), currentKaraoke);
        studio.getAw().getAudioWavePanel().updateView();
    }//GEN-LAST:event_toggleEnableKaraActionPerformed

    private void btnPlayWaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayWaveActionPerformed
        aw.play(Time.create(0L), Time.create(0L));
    }//GEN-LAST:event_btnPlayWaveActionPerformed

    private void btnPauseWaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseWaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPauseWaveActionPerformed

    private void btnStopWaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopWaveActionPerformed
        aw.stop();
    }//GEN-LAST:event_btnStopWaveActionPerformed

    private void btnPlayBeforeStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayBeforeStartActionPerformed
        Time msStop = aw.getTimeOfStartArea();
        Time msStart = Time.substract(msStop, Time.create(500L));
        aw.play(msStart, msStop);
    }//GEN-LAST:event_btnPlayBeforeStartActionPerformed

    private void btnPlayAfterStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayAfterStartActionPerformed
        Time msStart = aw.getTimeOfStartArea();
        Time msStop = Time.addition(msStart, Time.create(500L));
        aw.play(msStart, msStop);
    }//GEN-LAST:event_btnPlayAfterStartActionPerformed

    private void btnPlayAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayAreaActionPerformed
        Time msStart = aw.getTimeOfStartArea();
        Time msStop = aw.getTimeOfStopArea();
        aw.play(msStart, msStop);
    }//GEN-LAST:event_btnPlayAreaActionPerformed

    private void btnPlayBeforeEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayBeforeEndActionPerformed
        Time msStop = aw.getTimeOfStopArea();
        Time msStart = Time.substract(msStop, Time.create(500L));
        aw.play(msStart, msStop);
    }//GEN-LAST:event_btnPlayBeforeEndActionPerformed

    private void btnPlayAfterEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayAfterEndActionPerformed
        Time msStart = aw.getTimeOfStopArea();
        Time msStop = Time.addition(msStart, Time.create(500L));
        aw.play(msStart, msStop);
    }//GEN-LAST:event_btnPlayAfterEndActionPerformed

    private void btnModifyAreaGotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyAreaGotActionPerformed
        Time start = aw.getTimeOfStartArea();
        Time end = aw.getTimeOfStopArea();        
        studio.waveToCommand(start, end, true);
    }//GEN-LAST:event_btnModifyAreaGotActionPerformed

    private void btnAcceptGotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptGotActionPerformed
        Time start = aw.getTimeOfStartArea();
        Time end = aw.getTimeOfStopArea();        
        studio.waveToCommand(start, end, false);
    }//GEN-LAST:event_btnAcceptGotActionPerformed

    private void btnPlayBeforeStartSyllableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayBeforeStartSyllableActionPerformed
        if(currentKaraoke != null){
            Time msStop = currentKaraoke.getStartTimeAt(currentKaraoke.getSyllableIndex());
            Time msStart = Time.substract(Time.create(500L), msStop);
            aw.play(msStart, msStop);
        }
    }//GEN-LAST:event_btnPlayBeforeStartSyllableActionPerformed

    private void btnPlayAfterStartSyllableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayAfterStartSyllableActionPerformed
        if(currentKaraoke != null){
            Time msStart = currentKaraoke.getStartTimeAt(currentKaraoke.getSyllableIndex());
            Time msStop = Time.addition(msStart, Time.create(500L));
            aw.play(msStart, msStop);
        }
    }//GEN-LAST:event_btnPlayAfterStartSyllableActionPerformed

    private void btnPlayAreaSyllableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayAreaSyllableActionPerformed
        if(currentKaraoke != null){
            Time msStart = currentKaraoke.getStartTimeAt(currentKaraoke.getSyllableIndex());
            Time msStop = currentKaraoke.getEndTimeAt(currentKaraoke.getSyllableIndex());
            aw.play(msStart, msStop);
        }
    }//GEN-LAST:event_btnPlayAreaSyllableActionPerformed

    private void btnPlayBeforeEndSyllableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayBeforeEndSyllableActionPerformed
        if(currentKaraoke != null){
            Time msStop = currentKaraoke.getEndTimeAt(currentKaraoke.getSyllableIndex());
            Time msStart = Time.substract(Time.create(500L), msStop);
            aw.play(msStart, msStop);
        }
    }//GEN-LAST:event_btnPlayBeforeEndSyllableActionPerformed

    private void btnPlayAfterEndSyllableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayAfterEndSyllableActionPerformed
        if(currentKaraoke != null){
            Time msStart = currentKaraoke.getEndTimeAt(currentKaraoke.getSyllableIndex());
            Time msStop = Time.addition(msStart, Time.create(500L));
            aw.play(msStart, msStop);
        }
    }//GEN-LAST:event_btnPlayAfterEndSyllableActionPerformed

    private void btnPreviousSyllableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousSyllableActionPerformed
        int index = currentKaraoke.getSyllableIndex();
        
        if(index >= 0){
            index = index - 1 < 0 ? currentKaraoke.getSyllableCount() - 1 : index - 1;
        }
        
        currentKaraoke.setSyllableIndex(index);
        studio.getAw().getAudioWavePanel().updateView();
    }//GEN-LAST:event_btnPreviousSyllableActionPerformed

    private void btnNextSyllableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextSyllableActionPerformed
        int index = currentKaraoke.getSyllableIndex();
        
        if(index >= 0){
            index = index + 1 > currentKaraoke.getSyllableCount() - 1 ? 0 : index + 1;
        }
        
        currentKaraoke.setSyllableIndex(index);        
        studio.getAw().getAudioWavePanel().updateView();
    }//GEN-LAST:event_btnNextSyllableActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptGot;
    private javax.swing.JButton btnModifyAreaGot;
    private javax.swing.JButton btnNextSyllable;
    private javax.swing.JButton btnPauseWave;
    private javax.swing.JButton btnPlayAfterEnd;
    private javax.swing.JButton btnPlayAfterEndSyllable;
    private javax.swing.JButton btnPlayAfterStart;
    private javax.swing.JButton btnPlayAfterStartSyllable;
    private javax.swing.JButton btnPlayArea;
    private javax.swing.JButton btnPlayAreaSyllable;
    private javax.swing.JButton btnPlayBeforeEnd;
    private javax.swing.JButton btnPlayBeforeEndSyllable;
    private javax.swing.JButton btnPlayBeforeStart;
    private javax.swing.JButton btnPlayBeforeStartSyllable;
    private javax.swing.JButton btnPlayWave;
    private javax.swing.JButton btnPreviousSyllable;
    private javax.swing.JButton btnStopWave;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel paneEmbedWave;
    private javax.swing.JToolBar.Separator sepAudio01;
    private javax.swing.JToolBar.Separator sepAudio02;
    private javax.swing.JToolBar.Separator sepAudio03;
    private javax.swing.JToolBar.Separator sepAudio04;
    private javax.swing.JToggleButton toggleEnableKara;
    // End of variables declaration//GEN-END:variables
}
