# Copyright (C) 2020 util2
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# File menu
vmnFile \u30d5\u30a1\u30a4\u30eb
vmnFileOpenSubtitles \u5b57\u5e55\u3092\u958b\u304f
vmnFileSaveSubtitles \u5b57\u5e55\u3092\u4fdd\u5b58\u3059\u308b
vmnFileOpenVideo \u30d3\u30c7\u30aa\u30d5\u30a1\u30a4\u30eb\u3092\u958b\u304f
vmnFileOpenAudio \u30aa\u30fc\u30c7\u30a3\u30aa\u30d5\u30a1\u30a4\u30eb\u3092\u958b\u304f

# Display menu
vmnDisplay \u8868\u793a
vmnDisplayHideAll \u3059\u3079\u3066\u975e\u8868\u793a
vmnDisplayChat \u30c1\u30e3\u30c3\u30c8\u3092\u8868\u793a\u3059\u308b
vmnDisplayFiles P2P\u3092\u8868\u793a\u3059\u308b
vmnDisplayTranslate Display translate
vmnDisplayTime \u540c\u671f\u6642\u9593\u3092\u8868\u793a\u3059\u308b
vmnDisplayEdit \u30d3\u30c7\u30aa\u306e\u7de8\u96c6\u3092\u8868\u793a\u3059\u308b
vmnDisplayDrawing \u63cf\u753b\u3092\u8868\u793a\u3059\u308b

# Button
btnMessageTop \u30e1\u30c3\u30bb\u30fc\u30b8\u3092\u9001\u308b
