# Copyright (C) 2020 util2
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# File menu
vmnFile Fichier
vmnFileOpenSubtitles Ouvrir un fichier de sous-titres...
vmnFileSaveSubtitles Sauvegarder un fichier de sous-titres...
vmnFileOpenVideo Ouvrir une vid\u00e9o...
vmnFileOpenAudio Ouvrir un fichier audio...

# Display menu
vmnDisplay Affichage
vmnDisplayHideAll Cacher toutes les fen\u00eatres
vmnDisplayChat Affichage de la zone de discussion
vmnDisplayFiles Affichage de la zone de P2P
vmnDisplayTranslate Affichage de la zone de traduction
vmnDisplayTime Affichage de la zone de synchronisation
vmnDisplayEdit Affichage de la zone d'\u00e9dition
vmnDisplayDrawing Affichage de la zone de dessin

# Button
btnMessageTop Envoyer un message
